name: CI  
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Format all sv files
          uses: chipsalliance/verible-formatter-action@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
